### ISSUE TITLE
Schema Version 1 proposal

### ISSUE THREAD

**Issue by rahulgi** [rahafoundation/blockchain#2]
This is a proposal for the Version 1 blockchain schema. The version 0 schema has never been formally recorded, so it is included here as well. Feedback and corrections are welcomed.

# Version 0 schema
## Block schema
```
{
   "sequence": [int][block_sequence_no], // 0-indexed
   "version": 0,
   "prev_hash": [hashPtr][hash_of_the_previous_block], // null for first block
   "operations": [list(operation)][operations_contained_in_block]
}
```

## Operation schema
```
{
    "sequence": [int][operation_seqeuence_no], // 0-indexed
    "op": [string][choice(operation)],
    "data": [obj][operation_specific_data_obj]
}
```

## Choices
operation: `["CREATE_USER"]`

### CREATE_USER
```
{
    "full_name": [string][full_name],
    "user_name": [string][user_name],
    "admin": [string][user_name_of_inviting_user],
    "trust": [list(string)][user_names_of_trusted_users]
}
```

# Version 1 schema
## Block schema
```
{
   "sequence": [int][block_sequence_no], // 0-indexed
   "origin_created": [datetime][created_datetime_of_same_block_with_earliest_version], // new
   "version": 1,
   "prev_version_block": [hashPtr][ptr_to_same_block_in_previous_version_of_blockchain], // new
   "prev_hash": [hash][hash_of_the_previous_block], // null for first block
   "operations": [list][operations_contained_in_block]
}
```
## Operation schema
```
{
    "sequence": [int][operation_seqeuence_no], // 0-indexed
    "op_code": [string][choice(operation)],
    "creator_mid": [string][raha_assigned_uid], // new
    "data": [obj][operation_specific_data_obj]
}
```

## Choices
operation: `["REQUEST_INVITE", "TRUST"]`

### REQUEST_INVITE `// new`
```
{
    "full_name": [string][full_name],
    "to_mid": [string][mid_of_user_requesting_invite_from],
    "video_url": [url][url_of_invite_video],
}
```

### Trust `// new`
```
{
    "to_mid": [string][mid_of_user_to_trust],
}
```

## Notes
* A user, Alice, can only TRUST another user if there exists a path of TRUST to Alice from a user, Bob, who become a member of the network in a prior block. Block 0 is exempt from this restriction.

### Enable blockchain versioning
* added `prev_version_block` hashPtr to block schema
* added `origin_created` datetime to block schema
### Update operation schema
* add the `creator_mid` field.
  * All previously created users are now assigned an mid.
  * New users are assigned an mid upon joining Raha.
  * Mids can be changed via a to-be-added RENAME operation.
* renamed `op` field to `op_code`
* replaced `CREATE_USER` operation with `REQUEST_INVITE` and `TRUST` operations.
  * All previously created users now have `REQUEST_INVITE` and `TRUST` operations in the same block sequence number they were created in.

**Comment by rahulgi** [comment]
Question: Should the constraint "A user cannot REQUEST_INVITE and TRUST another user in the same block except in block 0. This prevents the spontaneous creation of an isolated trusted cluster." be relaxed to only another user who also has a REQUEST_INVITE operation in the same block? This would allow a user to, for example, automatically create a trust relationship with the user who invited them (as we do with the CREATE_USER operation in V0).

**Comment by rahulgi** [comment]
Concrete conflict from this constraint - Iris and Vincent are both created and trust each other all within one block. However, Mark also trusts them both. I think the constraint should actually be:
"If a user has a REQUEST_INVITE and TRUST operation in the same block, they must also within the same block be the recipient of a TRUST operation from a user who has been the recipient of a TRUST operation in a previous block."

**Comment by rahulgi** [comment]
Right... a simpler way to put this is definitely: "To TRUST another user, in the same or earlier block that user must be TRUSTed by a user who became a member (REQUEST_INVITE + TRUSTed) of the network in a prior block. The exception is block 0."

**Comment by markulrich** [comment]
Looks great!! Let's turn this into a PR!

I would say for now it should not matter if an operation is in the same/earlier block, just if an operation has an earlier sequence number, since initially we might be creating blocks very infrequently. This may pose race conditions since sequence number is not known until block creation time (at which point we'll probably do it based on timestamp), but I don't think we need to worry about that right now - some people's transactions may later not make it into blockchain. Nothing is "real" and fully verified until it's in the blockchain.

**Comment by rahulgi** [comment]
"A user, Alice, can only TRUST another user if there exists a path of TRUST to Alice from a user, Bob, who become a member of the network in a prior block" ... I think that works and is flexible enough for us to not have to worry about infrequent block creation or sequence numbers/timestamps. But.. should probably sleep given how messy this is getting lol :P

**Comment by osdiab** [comment]
This is cosmetic, but can we just make a folder called `specs` in the repo and put this in there? more accessible for posterity and can use the full PR/commenting facilities github provides.

**Comment by osdiab** [comment]
The choices stuff is just a union type right? just checking lol, not really seen people express it that way

**Comment by osdiab** [comment]
Looks nice!

**Comment by rahulgi** [comment]
Yes, that's a good idea. i'll make a PR for it.

And.. lol. I don't have any schema definition languages memorized, so I just kinda winged it :P but yes.
